"""
Python program for find differnce between two given string.

Description : You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

"""
import random

def shuffle_string(string1):
    """This function shuffles the given string"""
    try:
        l = list(string1)
        random.shuffle(l)
        result = ''.join(l)
        print("String after shuffling is:", result)
        return result
    except Exception as e:
        print(e)
        return None

def add_letter(string1, letter):
    """This function adds a new letter to the existing string"""
    try:
        # Insert the letter at a random position
        position = random.randint(0, len(string1))
        new_string = string1[:position] + letter + string1[position:]
        print("String after adding new letter:", new_string)
        return new_string
    except Exception as e:
        print(e)
        return None

def find_added_letter(s, t):
    """This function finds the letter that was added to t"""
    try:
        count_s = {}
        count_t = {}

        for char in s:
            count_s[char] = count_s.get(char, 0) + 1

        for char in t:
            count_t[char] = count_t.get(char, 0) + 1

        for char in count_t:
            if count_t[char] != count_s.get(char, 0):
                return char
        return None
    except Exception as e:
        print(e)
        return None

try:
    s = input("Enter the first string to check difference: ")

    shuffled_s = shuffle_string(s)

    if shuffled_s is not None:
        letter = input("Enter the letter you want to add to the string: ")

        new_string = add_letter(shuffled_s, letter)

        if new_string is not None:
            added_letter = find_added_letter(shuffled_s, new_string)
            if added_letter:
                print("The letter added to the string is:", added_letter)
            else:
                print("No difference found")
except Exception as e:
    print(e)
